### ISSUE TITLE
SHYFT-18

### ISSUE THREAD

**Issue by skavhaug** [statkraft/shyft#1]
# Add Arome interpolation to Shyft.

Arome is a distributed forecast dataset delivered from met.no, that comes in netcdf files. Typically, it contains temperature, precipitation, relative humidity, radiation, wind speeds etc. Resolution is on km-scale, with the current dataset on 2.5km grid. The dataset also contains information about the projection used. In this task, we create input datasets for SHyFT from these data, in a fairly efficient manner. The arome reading functionality will be in terms of a repository.

**Comment by jfburkhart** [comment]
There are a few separate issues contained herein. I would propose the following approach:

* create a repository that can open the Arome netcdf files, and extract a geographic subset to input source types of the timeseries centered at each grid cell in the netcdf (no interpolation, just simple creation of input source types)
* provide (as an option in the repository?) a mechanism whereby interpolation is done to the cells.

This would provide a bit more flexibility -- and hopefully reuseability -- going forward with netcdf input files of higher/lower resolution.

**Comment by skavhaug** [comment]
Regarding the second point above - interpolation needs to take into account for instance height correction (and later other effects like cell normal). This is done in shyft today and the existing routines for interpolation can be used for this point.

**Comment by yisak** [comment]
My concerns with passing each AROME grid point as source and doing the interpolation in shyft are:
* Currently the interpolation does not use shape information. Since we are now using polygons which are mostly squares (1x1km), doing the interpolation without taking shape into account is reasonable. But this will be questionable when we move to more irregular polygons with varying shapes and sizes (homogeneous cell types, small subcatchments, etc...). One alternative to avoid this maybe to have a convention of always splitting (intersecting) the polygons into regular square grids.
* The current interpolation takes relatively long time to finish. For NeaNidelva with around 8-9 stations and around 2500 points to interpolate to, the interpolation takes longer time than the simulation itself. And in the case of AROME with hundreds of points, it was just too slow. 
* When extracting data using a bounding box, a lot of points which won't be used in the interpolation will be extracted. Won't this add additional burden to the interpolation routine by supplying more points to filter from?

**Comment by skavhaug** [comment]
Can you elaborate on the first point there? I don't understand why more
irregularly shaped polygons affects this.

For point two, we should look into this properly. There are several ways of
overcoming this, and different levels.

Three: The full extraction and conversion to source vectors takes 5 secs,
which is not a lot. The interpolation routines only consider the nearest
points, so this is more a memory concern than a run time concern. If not,
we have done something stupid :)

Ola Skavhaug, PhD
Founder, Expert Analytics AS

**Comment by yisak** [comment]
Attempt to elaborate on the first point regarding irregularly shaped polygons: When assigning weights to the points from which a value is interpolated for a cell, the weights are computed using the distance between the points and the centroid of the cell. The shorter the distance the higher the weight. But the closeness of a point to the centroid of an irregularly shaped cell does not necessarily represent the weight of its contribution. A point far from the centroid maybe be lying inside the cell while a point closer to the centroid maybe outside the cell.

**Comment by skavhaug** [comment]
Ok, I see. I am not sure I buy the argument that the centroid is not the most representative single point of most cells, but it is of course possible to construct counter examples showing you have a point :)

I think the solution of this would be to use triangular cells, since these are easy to fit to general topologies, and are convex. Also the centroid of a convex shape is probably a good representative point. This ties into the mass flux discussion as well, which eventually have to assume convex cells, at least.

I suggest we leave this discussion for this PR, and instead create a new issue discussing cell shapes in general. It should probably be an epic.

**Comment by sigbjorn** [comment]
about interpolation and speed:
a) We could easily speed up interpolation using multiple threads (will do so)
b) btk is in effect for temperature, - I guess IDW, linear , is better when you are passing an arome-grid.
   (needs a minor fix in run_interpolation, to have it select IDW for temperature if parameterized to do that).
