### ISSUE TITLE
OSP-1: Documentation

### ISSUE THREAD

**Issue by skavhaug** [statkraft/shyft#2]
* Improve README.md so that all significant contributors are mentioned, and redirects to  install procedures and basic documentation (in separate repos).
* Start filling wiki with relevant docs on build/install, testing, how to contribute etc.

**Comment by FrancescAlted** [comment]
I also would start adding a Sphinx doc directory right in a new `doc/`.  Using Restructured text has the advantage that github can render the documents pretty nicely, and they can be referred directly from the README. I can start with the existing set of docs at: `https://bitbucket.org/enkiopensource/enki/src/311ccd384e2a87f3202e6fe948b9e61fc462e0d8/doc/sphinx/?at=refactor`.

Also, and in order to avoid spreading docs too much, I would prefer to keep all the docs (including docs for developers) centralized in the same sphinx sources.

**Comment by sigbjorn** [comment]
shyft-doc repository is now created for this purpose.
We keep the shyft source as clean as we can, and put documentation, etc into shyft-doc.
Currently I have put up the doxygen for the shyft, plus sparx ea file describing the roles, system, current deployment, a sample workflow. 
I think thats a start, and we have established a starting point for documentation.
There is still a lot more to document (everything from build/setup.. to practical use .. theory references etc.)
