### ISSUE TITLE
__init__ file clean up

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#216]
With python 3 there are some changes to imports. I get some strange behavior in a notebook if I create a dictionary referencing a class buried within shyft:
    
     `SimDict = {'start_datetime': "2013-09-01T00:00:00",
          'run_time_step': 86400, # seconds, daily
          ',number_of_steps': 365, # one year
          'region_model_id': 'demo', #a unique name identifier of the simulation
          'domain': {'EPSG': 32633,
                        'nx': 400,
                        'ny': 80,
                        'step_x': 1000,
                        'step_y': 1000,
                        'lower_left_x': 100000,
                        'lower_left_y': 6960000},
          'repository': {'class': shyft.repository.netcdf.cf_region_model_repository.CFRegionModelRepository,
                             'params': {'data_file': 'netcdf/orchestration-testdata/cell_data.nc'}},

          }`

The cell executes with error message:

`AttributeError: module 'shyft' has no attribute 'repository'
`

If I execute first:

`from shyft.repository.netcdf.cf_region_model_repository import CFRegionModelRepository`

Then there are no problems. I believe we need to modify the __init__ files to expose the subpackages as public attributes, but I'm not so familiar with the recent requirements regarding __init__.

**Comment by sigbjorn** [comment]
Hi,

I think I see your point here, and you might have a look into it.

python require us to import, explicit,

and as long as we don't get into the 'big inhale' I am open for any improvement.
Ref.
 [python 3.6 modules ](https://docs.python.org/3/tutorial/modules.html)

and section 6.4.1 .

In ordinary python code, this should be no problem, since we are explicit,
like in your example that work.

**Comment by runeyosh** [comment]
Fixed, see issue #378
