### ISSUE TITLE
Strange problem with interpolation

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#221]
In 
[demo.zip](https://github.com/statkraft/shyft/files/1580660/demo.zip)

(rename to .tgz) there are two files. The simulation-api.py file has odd behavior (set a break point at ~275). run_interpolation returns False with btk and True with idw, but in both cases skips data in the beginning of the series. It is most likely due to a nan value in the precipitation.nc file, but for whatever reason run_nea_nidelva.py (using yaml configurations) handles this and the simple api example fails.

**Comment by sigbjorn** [comment]
Hi,
It turned out it was the formatting of parsing of the ISO 8601 string, month and day intermixed, so it was running for the period 2013-01-09T00:00:00Z, but the intention was clearly 2013-09-01T00:00:00Z.
The correct string would be "%Y-%m-%dT%H:%M:%S" if using strptime.

This is also consistent with the results, showing up only at the end of the period, where the data is defined.

A minimal function to pull excange the config to a time-axis could be like:
```python
def time_axis_from_dict(c:dict)->api.TimeAxisFixedDeltaT:
     return api.TimeAxisFixedDeltaT(
         start=int(time.mktime(time.strptime(c['start_datetime'],'%Y-%m-%dT%H:%M:%S'))),
         delta_t=int(c['run_time_step']),
         n=int(c['number_of_steps'])
     )
```


Also notice to set a state before using revert_to_initial_state(),

e.g.:
```python
region_model.run_interpolation(region_model.interpolation_parameter, ta, region_env)
region_model.set_states(state_repo.get_state(0))
region_model.run_cells()
```

**Comment by jfburkhart** [comment]
hanging head in shame... and closing!
