### ISSUE TITLE
geo_location_criteria / selection_criteria

### ISSUE THREAD

**Issue by eriktjotta** [statkraft/shyft#232]
Hi all!

The netcdf-repositories (i.e arome_data_repository/ec_data_repository/arome_concat_repository/...) has the variable  selection_criteria / bounding_box both at the class level and at the public function (geo_location_criteria) level. I.e:

```
def __init__(self, epsg, filename, nb_pads=0, nb_fc_to_drop=0, selection_criteria=None, padding=5000.):

def get_forecast(self, input_source_types, utc_period, t_c, geo_location_criteria):
```

Some questions on this:

Is there a good reason for having this as a class variable?

If so, it seems dangerous/confusing to re-initialize the class when get_forecast / get_timeseries is called as seems to be the practice:

```
def _get_data_from_dataset(self, dataset, input_source_types, fc_selection_criteria_v,
                           geo_location_criteria, concat=True, ensemble_member=None):

	if geo_location_criteria is not None:
    	self.selection_criteria = geo_location_criteria
```

In the concat_data_repository, I am tempted to omit selection_criteria  as a class variable. Any objections?

Best,
Erik

**Comment by yisak** [comment]
Hi

I agree with you that this can be confusing and that it should not be a class variable.

The main reason it was done like that is because of how GeoTsRepository was set up for SMG at Statkraft. Unfortunately, in this case, the actual climate data for stations and the their geographic coordinates reside in two different locations (databases). The actual data is stored in SMG and the the gis info for the stations is stored in the GIS database. The work-around used during the initial development was to pass in geo info of the stations during initialization of the GeoTsRepo and already decide the available stations at initialization. Then the methods get_timeseries could be called without any geo_location_criteria and it simply returns data for the stations you initialized it with. So if you look at the get_timeseries method of ssa_geo_ts_repository.GeoTsRepository (https://github.com/statkraft/shyft/blob/master/shyft/repository/service/ssa_geo_ts_repository.py#L352) you will see that geo_location_criteria is not used.

I have later made a subclass of ssa_geo_ts_repository.GeoTsRepository which avoids the need of this pre-definition of stations to fetch (https://github.com/statkraft/internal/blob/master/hydrology/shyft_internal/shyft_config/orchestration/statkraft_shyft_config.py#L15896)

So I would vote for the removal of this argument from the initialization and updating of corresponding tests according to this change.

Yisak

**Comment by jfburkhart** [comment]
I agree also. There have been a number of decisions made early on that were based on having to co-locate data based on two different `sources` one for geo and one for timeseries. It causes a good degree of confusion in the more typical use case of reading netcdf, etc.

**Comment by eriktjotta** [comment]
Note that I am not suggesting that we refactor the existing repositories; I am just seeking guidelines to follow for the new repository `concat_data_repository` which generalizes the `ec_concat_data_repository` and  `arome_concat_data_repository`, and extends to ensemble forecasts.

**Comment by jfburkhart** [comment]
@eriktjotta  will set up the new `concat_data_repository` using these guidelines. The refactor discussion can be left to #233
