### ISSUE TITLE
collection criteria as classes

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#234]
Per #233 it was agreed the selection criteria should be classes. `geo_location_criteria` will become a shapely polygon. `fc_selection_criteria` will be a custom class.

This issue is to create that class.

**Comment by yisak** [comment]
Hi,

How about defining the `fc_selection_criteria` class as below? I also moved the validation code inside this class so that this validation does not to be coded under every repository.

 ```python
from shyft import api


class ForecastSelectionCriteriaError(Exception):
    pass

class ForecastSelectionCriteria(object):
    def __init__(self, **kwargs):
        cri_lst = [(k, v) for k, v in kwargs.items()]
        is_not_none = [cri[1] is not None for cri in cri_lst]
        if sum(is_not_none) != 1:
            raise ForecastSelectionCriteriaError('Only one of the selection criteria should be specified!')
        self._selected_criterion = cri_lst[is_not_none.index(True)]
        self._validate()

    @property
    def criterion(self):
        return self._selected_criterion

    def _validate(self):
        k, v = self._selected_criterion
        if k == 'forecasts_created_within_period':
            if not isinstance(v, api.UtcPeriod):
                raise ForecastSelectionCriteriaError(
                    "'forecasts_created_within_period' selection criteria should be of type api.UtcPeriod.")
        elif k == 'forecasts_with_start_within_period':
            if not isinstance(v, api.UtcPeriod):
                raise ForecastSelectionCriteriaError(
                    "'forecasts_with_start_within_period' selection criteria should be of type api.UtcPeriod.")
        elif k == 'forecasts_that_cover_period':
            if not isinstance(v, api.UtcPeriod):
                raise ForecastSelectionCriteriaError(
                    "'forecasts_that_cover_period' selection criteria should be of type api.UtcPeriod.")
        elif k == 'latest_available_forecasts':
            if not all([isinstance(v, dict), isinstance(v['number of forecasts'], int),
                        isinstance(v['forecasts_older_than'], int)]):
                raise ForecastSelectionCriteriaError(
                    "'latest_available_forecasts' selection criteria should be of type dict.")
        elif k == 'forecasts_at_reference_times':
            if not isinstance(v, list):
                raise ForecastSelectionCriteriaError(
                    "'forecasts_at_reference_times' selection criteria should be of type list.")
        else:
            raise ForecastSelectionCriteriaError("Unrecognized forecast selection criteria.")


# Examples
# Valid initialization
s=ForecastSelectionCriteria(forecasts_created_within_period=api.UtcPeriod(0,3600))
s.criterion
Out[3]: ('forecasts_created_within_period', <shyft.api._api.UtcPeriod at 0xc9c39ef538>)

# Invalid because criterion type not correct

s=ForecastSelectionCriteria(forecasts_created_within_period=3600)
Traceback (most recent call last):
  File "C:\Miniconda3\envs\shyft\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-c5c192c070df>", line 1, in <module>
    s=ForecastSelectionCriteria(forecasts_created_within_period=3600)
  File "G:/Work/shyft/scripts/shyft_run/fc_selection_criteria.py", line 21, in __init__
    k, v = self._selected_criterion
  File "G:/Work/shyft/scripts/shyft_run/fc_selection_criteria.py", line 32, in _validate
    raise ForecastSelectionCriteriaError(
ForecastSelectionCriteriaError: 'forecasts_created_within_period' selection criteria should be of type api.UtcPeriod.
s=ForecastSelectionCriteria(forecasts_created_within_period=api.UtcPeriod(0,3600), forecasts_that_cover_period=api.UtcPeriod(0,3600))
Traceback (most recent call last):
  File "C:\Miniconda3\envs\shyft\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-651295346fd3>", line 1, in <module>
    s=ForecastSelectionCriteria(forecasts_created_within_period=api.UtcPeriod(0,3600), forecasts_that_cover_period=api.UtcPeriod(0,3600))
  File "G:/Work/shyft/scripts/shyft_run/fc_selection_criteria.py", line 19, in __init__
ForecastSelectionCriteriaError: Only one of the selection criteria should be specified!

# Invalid because criterion is not recognized (defined)

s=ForecastSelectionCriteria(blablabla=api.UtcPeriod(0,3600))
Traceback (most recent call last):
  File "C:\Miniconda3\envs\shyft\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-19499f036b79>", line 1, in <module>
    s=ForecastSelectionCriteria(blablabla=api.UtcPeriod(0,3600))
  File "G:/Work/shyft/scripts/shyft_run/fc_selection_criteria.py", line 21, in __init__
    k, v = self._selected_criterion
  File "G:/Work/shyft/scripts/shyft_run/fc_selection_criteria.py", line 51, in _validate
ForecastSelectionCriteriaError: Unrecognized forecast selection criteria.
```

**Comment by eriktjotta** [comment]
Can anyone explain the benefits of having it as classes vs dictionaries?

**Comment by jfburkhart** [comment]
I believe some of the mentioned benefits were related to testing, the type can be more specific. This would further benefit one's workflow as well with IDE support.

Personally, I have a preference for classes because of the '.' notation and tab completion. Overall, it provides more control.

**Comment by jfburkhart** [comment]
In fact, here's how much I like them:

```

class Structure(dict):
    def __getattr__(self, attr):
        return self[attr]
    def __setattr__(self, attr, value):
        self[attr] = value

    def set_with_dict(self, D):
        """ set attributes with a dict """
        for k in D.keys():
            self.__setattr__(k, D[k])

```

I don't use it anymore, but my code used to be loaded with `Structure` instances. 
;)

**Comment by eriktjotta** [comment]
But what about Yisaks suggestion above? He is asking for feedback, I just want to help him get a discussion going on his concrete class suggestion. 

I see the benefit of putting the validation in the class so it doesn't have to replicated across repositories. But our goal is to only have one concatenated repository anyhow - so that is perhaps not the big selling point...? Further, I don't see this concrete class suggestion benefiting from tab-completion and the IDE support will be available independently of which data structure we chose. What are the benefits we want to achieve with respect to testing? 

Perhaps somebody can explain the drawbacks of existing dictionaries and how we want our class to improve on this...? That would make it easier to comment on Yisaks suggestion.

**Comment by yisak** [comment]
Here are some of the advantages of defining it as the class above:

- As already mentioned, the validation code and the documentation does not have to be replicated across repositories. It is not given that we will have only one data source (which is concat netcdf file today) from which we read multiple forecasts. Concat netcdf is just one of many possible data sources.

- It is more meaningful to type check `fc_selection_criteria` argument and control that it is of a concrete type (which could be `class ForecastSelectionCriteria`) than checking if it is a dictionary. If it is of type dictionary then it can be any dictionary. But an instance of a specific class we have defined from this purpose will be unequivocal when doing type checking.

-  When using a dictionary as argument, which is a mutable object, one risks that the values of the variables one passed in can be overwritten (modified) inside the function the dictionary was passed to. But if we use an instance of `ForecastSelectionCriteria` then we do not risk that the attribute `criterion`, will be modified since `criterion` is a property and cannot therefore be modified (cannot be set).

**Comment by eriktjotta** [comment]
Thanks for clarifying; makes sense to me.
