### ISSUE TITLE
utc.time behavior, expected?

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#363]
Hello, working with api.Calendar. I am having the following behavior, it is expected?

```
In [280]: utc = api.Calendar('UTC')

In [281]: shyft_now = api.utctime_now(); dt_now = dt.datetime.now()

In [282]: dt.datetime.fromtimestamp(shyft_now)
Out[282]: datetime.datetime(2018, 11, 6, 7, 15, 13)

In [283]: dt_now
Out[283]: datetime.datetime(2018, 11, 6, 7, 15, 13, 474593)

In [284]: dt.datetime.fromtimestamp(utc.trim(shyft_now, api.Calendar.HOUR))
Out[284]: datetime.datetime(2018, 11, 6, 7, 0)

In [285]: dt.datetime.fromtimestamp(utc.trim(shyft_now, api.Calendar.DAY))
Out[285]: datetime.datetime(2018, 11, 5, 18, 0)
```
All commands were executed within a few seconds. I am troubled by the last result.

**Comment by felixmatt** [comment]
Hi John. What's the result you would expect?

I guess you mean that the output should be rounded to whole days (hour=0)?

Note that `dt.datetime.fromtimestamp` returns tz's **local time** from a POSIX timestamp.
utc.trim rounds time t down to the nearest calendar time-unit delta_t taking the **calendar time-zone** (here utc) into account. So, you are operating on a utc timestamp.
You receive the expected behavior by using `dt.datetime.utcfromtimestamp`.

Example:

`In [22]: import datetime as dt`

`In [23]: utc = api.Calendar('UTC')`

`In [24]: shyft_now = api.utctime_now()`

`In [25]: dt.datetime.utcfromtimestamp(utc.trim(shyft_now, api.Calendar.DAY))`
`Out[25]: datetime.datetime(2018, 11, 6, 0, 0)`

but

`In [26]: dt.datetime.fromtimestamp(utc.trim(shyft_now, api.Calendar.DAY))`
`Out[26]: datetime.datetime(2018, 11, 6, 1, 0)`

Is that what you meant?

**Comment by sigbjorn** [comment]
:+1:  .. shyft is explicit about time and Calendar. Time is just a number, SI-units. Calendar can convert between calendar-coordinates (Y,M,D,h,m,s, and friends) and time (again a number).    python datetime is broken in so many ways, including mixing time/Calendar concepts, and 'hidden -implicit time-zone assumptions'.  It's very quick to loose track of what's going on behind the scenes. In shyft, time is a number, and everything people know about numbers should apply. Calendar is explicit, and should hopefully give few surprises when applied. (or we would have to fix it :-)

**Comment by jfburkhart** [comment]
@felixmatt yes, that must be what I was missing.. .the `utcfromtimestamp`. Thanks!

**Comment by felixmatt** [comment]
Reopening issue as I also have some behaviour I just came across when looking into this.
When using `api.Calendar().trim`, microseconds seem to be unaffected. @sigbjorn is that intentional?

e.g.:
`In [22]: from shyft import api`
`In [23]: utc = api.Calendar('UTC')`
`In [12]: shyft_now = api.utctime_now()`

`In [13]: print(shyft_now)`
`2018-11-06T19:04:42.767224Z`

`In [14]: print(utc.trim(shyft_now, api.Calendar.DAY))`
`2018-11-06T00:00:00.767224Z`

**Comment by sigbjorn** [comment]
No, -that's not wanted, so that we can fix. I would prefer a separate issue on trim and micro-seconds.
