### ISSUE TITLE
Unexpected results from DST handling in Calendar.add

### ISSUE THREAD

**Issue by eivindlm** [statkraft/shyft#409]
The result of Calendar.add(t0, Calendar.HOUR, 1) is unexpected for 2019-3-31 when t0+Calendar.HOUR lies in the hour 02:00-03:00 (GMT+1), i.e. the "undefined" hour when changing to DST. It may look like an hour is subtracted instead of added to the result?

The following code:
```
from shyft.api import Calendar
cal = Calendar("Europe/Oslo")

# Each entry in the list contains a start time t0 along with the expected result from t0+Calendar.HOUR
times = [(cal.time(2019,3,31,0,59,59), cal.time(2019,3,31,1,59,59), "Last second before"),
         (cal.time(2019,3,31,1, 0, 0), cal.time(2019,3,31,3, 0, 0), "First intersection with DST"),
         (cal.time(2019,3,31,1,30, 0), cal.time(2019,3,31,3,30, 0), "Contains DST"),
         (cal.time(2019,3,31,1,59,59), cal.time(2019,3,31,3,59,59), "Last intersection with DST"),
         (cal.time(2019,3,31,2,00,00), cal.time(2019,3,31,4,00,00), "From 'invalid' time"),
         (cal.time(2019,3,31,3,00,00), cal.time(2019,3,31,4,00,00), "Last second after")  
]

for t0, expected, text in times:
    result = cal.add(t0, Calendar.HOUR, 1)
    if result != expected:
        print(f"*** Error: {text}")
        print(f"       t0: {cal.to_string(t0)}")
        print(f"   Result: {cal.to_string(result)}")
        print(f" Expected: {cal.to_string(expected)}")
```
Yields the following result:
```
*** Error: First intersection with DST
       t0: 2019-03-31T01:00:00+01
   Result: 2019-03-31T01:00:00+01
 Expected: 2019-03-31T03:00:00+02
*** Error: Contains DST
       t0: 2019-03-31T01:30:00+01
   Result: 2019-03-31T01:30:00+01
 Expected: 2019-03-31T03:30:00+02
*** Error: Last intersection with DST
       t0: 2019-03-31T01:59:59+01
   Result: 2019-03-31T01:59:59+01
 Expected: 2019-03-31T03:59:59+02
```

**Comment by sigbjorn** [comment]
Hi,

 yes, this is an issue, that I _think_ we can solve with few side-effects.


As pointed out in the source code, (have a look into utctime_utilties.h, add method),
the dst handling is defined by one simple rule, (ref the note in the doc-section)
that is

*  context-free(i.e. the rule is state-less, does not have to carry state from previous adds etc.), 

*  gives speed of computation(stateless, immutable), 

*  symmetric evaluation add;diff, and over years iterations etc. etc., 

*  works over history of dst changes, including historical and future.

but it do have it's limitations, mostly set by the inherent problems dealing with dst and calendar in general.

Tests for this can be found in test/utctime_utilties_test.cpp

Usually, using calendar for adding delta-T at hour-level is not recommended due to performance.

If you would like to add 3600 s, to t0, just write t0+3600. Using a calendar in that context is just incredible waste of cpu-time compared to just using numeric add!

That set aside,  given this case, - I think it can be improved, to solve this issue, where the delta-t is less than the dst-shift (for practical purposes, 1h) by adding once simple exception that if the effective deltaT is less or equal to an hour, then just ordinary arithmetic applies.
