### ISSUE TITLE
TimeSeries.min_max_check_linear_fill behaves different for instant and average time-series

### ISSUE THREAD

**Issue by eistaa** [statkraft/shyft#422]
The `TimeSeries.min_max_check_linear_fill` behaves different with regard to trailing NaN values between time-series with instant point interpretation (`POINT_INSTANT_VALUE`) and average point interpretation (`POINT_AVERAGE_VALUE`).

With an instant time-series all the trailing NaN values are preserved, as I expect it to do. While with an average time-series only the final NaN value is preserved.

Example:
``` python
from math import isnan

import shyft.api as sa

def values_equal(values1, values2):
    return all((isnan(v1) and isnan(v2)) or abs(v1 - v2) <= 1e-4 for v1, v2 in zip(values1, values2))

# the time-series value is clearly between the boundaries
min_value = 0.
ts_value = 5.
max_value = float('nan')  # no boundary

# the time-series are equal except for the point interpretation
# - instant
instant_ts = sa.TimeSeries(sa.TimeAxis(0, 3600, 18),
                           [float('nan')]*6 + [5.]*6 + [float('nan')]*6,
                           sa.POINT_INSTANT_VALUE)
# - average
average_ts = sa.TimeSeries(sa.TimeAxis(0, 3600, 18),
                           [float('nan')]*6 + [5.]*6 + [float('nan')]*6,
                           sa.POINT_AVERAGE_VALUE)

# with the instant time-series the trailing sequence of nan-values are preserved
instant_minmax_ts = instant_ts.min_max_check_linear_fill(v_min=0, v_max=float('nan'))
print(instant_minmax_ts.values)
# this assert pass
assert values_equal(instant_ts.values, instant_minmax_ts.values)

print()

# with the average time-series the trailing sequence of nan-values are not preserved, except for the last
average_minmax_ts = average_ts.min_max_check_linear_fill(v_min=0, v_max=float('nan'))
print(average_minmax_ts.values)
# this assert fail
assert values_equal(average_ts.values, average_minmax_ts.values)
```
This outputs:
````
INSTANT
[nan nan nan nan nan nan  5.  5.  5.  5.  5.  5. nan nan nan nan nan nan]

AVERAGE
[nan nan nan nan nan nan  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5. nan]
Traceback (most recent call last):
  File "C:/Users/uxxxxx/.PyCharm2018.3/config/scratches/buffer2_5.py", line 38, in <module>
    assert values_equal(average_ts.values, average_minmax_ts.values)
AssertionError
```

**Comment by sigbjorn** [comment]
Thanks for the report.

This function is not about preserving nans, - it's about marking values that exceeds the limits as nan, then doing best effort filling in replacement values, using surrounding values, according to rules and the underlying time-series point-interpretation. While at it, we can ensure this is more clear in the doc-string as well.

So we should expect them to behave different for different inputs,  in this case, the point-interpretation of the underlying time-series.

A stair-case series (POINT_AVERAGE_VALUE), and the algo, if encounter a nan,  will look backward to find a filler, it should do so for the last value in the sequence as well.  So I guess that is your expectation. We will fix that.

A linear ts (POINT_INSTANT_VALUE), needs a  next valid point to repair a gap. Since there are no such values in your test-gap, it fails to fill in non-nans.
